[workspace]
resolver = "2"
members = ["rumi-core", "rumi-proto", "rumi-domains", "rumi"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yzavyas/x.uma"
authors = ["Yashodeep Vyas"]

[workspace.dependencies]
# Internal crates
rumi-core = { path = "rumi-core" }
rumi-proto = { path = "rumi-proto" }
rumi-domains = { path = "rumi-domains" }

# Proto & serialization
prost = "0.13"
prost-types = "0.13"

# Testing
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"

# Development
thiserror = "2"
